# Restaurant Rating System

### importing dependies

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
# import warnings
import chardet

from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

### loding the dataset

In [2]:
df = pd.read_csv("dataset.csv", encoding="utf-8-sig")

df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [3]:
with open("dataset.csv", "rb") as f:
    result = chardet.detect(f.read())

result

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

In [4]:
# !pip install chardet

In [5]:
df = df.replace('�', '', regex=True)
df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208           stanbul   
9547        5908749                Ceviz Aac۱           208           stanbul   
9548        5915807                     Huqqa           208           stanbul   
9549        5916112                  Ak Kahve           208           stanbul   
9550        5927402  Walter's Coffee Roastery           208           stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke Karamustafa Paa Mahallesi, R۱ht۱m Cadd...   
9547  Kouyolu Mahallesi, Muhittin st_nda Caddesi, No...   
9548  Kuru_eme Mahallesi, Muallim Naci Caddesi, No 5...   
9549  Kuru_eme Mahallesi, Muallim Naci Caddesi, No 6...   
9550  Cafeaa Mahallesi, Bademalt۱ Sokak, No 21/B, Ka...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                     Karak_y   
9547                                     Kouyolu   
9548                                    Kuru_eme   
9549                                    Kuru_eme   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                   Karak_y, stanbul   28.977392   
9547                                   Kouyolu, stanbul   29.041297   
9548                                  Kuru_eme, stanbul   29.034640   
9549                                  Kuru_eme, stanbul   29.036019   
9550                                      Moda, stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

### data set cleaaning

In [6]:
df = df.drop(columns=[
    'Restaurant Name','Address','Locality','Locality Verbose',
    'Currency','Rating color','Rating text',
    'Switch to order menu','Longitude','Latitude','Cuisines','City', 'Restaurant ID','Country Code'
])

In [7]:
df.isnull().sum()

Average Cost for two    0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Price range             0
Aggregate rating        0
Votes                   0
dtype: int64

In [8]:
df['Has Online delivery'] = df['Has Online delivery'].map({'Yes':1,'No':0})
df['Has Table booking'] = df['Has Table booking'].map({'Yes':1,'No':0})
df['Is delivering now'] = df['Is delivering now'].map({'Yes':1,'No':0})

In [9]:
numeric_df = df.select_dtypes(include=['int64','float64'])
numeric_df

Average Cost for two  Has Table booking  Has Online delivery  \
0                     1100                  1                    0   
1                     1200                  1                    0   
2                     4000                  1                    0   
3                     1500                  0                    0   
4                     1500                  1                    0   
...                    ...                ...                  ...   
9546                    80                  0                    0   
9547                   105                  0                    0   
9548                   170                  0                    0   
9549                   120                  0                    0   
9550                    55                  0                    0   

      Is delivering now  Price range  Aggregate rating  Votes  
0                     0            3               4.8    314  
1                     0            3               4.5    591  
2                     0            4               4.4    270  
3                     0            4               4.9    365  
4                     0            4               4.8    229  
...                 ...          ...               ...    ...  
9546                  0            3               4.1    788  
9547                  0            3               4.2   1034  
9548                  0            4               3.7    661  
9549                  0            4               4.0    901  
9550                  0            2               4.0    591  

[9551 rows x 7 columns]

In [10]:
numeric_df.corr()['Aggregate rating'].sort_values(ascending=False)

Aggregate rating        1.000000
Price range             0.437944
Votes                   0.313691
Has Online delivery     0.225699
Has Table booking       0.189998
Average Cost for two    0.051792
Is delivering now       0.019180
Name: Aggregate rating, dtype: float64

In [11]:
df

Average Cost for two  Has Table booking  Has Online delivery  \
0                     1100                  1                    0   
1                     1200                  1                    0   
2                     4000                  1                    0   
3                     1500                  0                    0   
4                     1500                  1                    0   
...                    ...                ...                  ...   
9546                    80                  0                    0   
9547                   105                  0                    0   
9548                   170                  0                    0   
9549                   120                  0                    0   
9550                    55                  0                    0   

      Is delivering now  Price range  Aggregate rating  Votes  
0                     0            3               4.8    314  
1                     0            3               4.5    591  
2                     0            4               4.4    270  
3                     0            4               4.9    365  
4                     0            4               4.8    229  
...                 ...          ...               ...    ...  
9546                  0            3               4.1    788  
9547                  0            3               4.2   1034  
9548                  0            4               3.7    661  
9549                  0            4               4.0    901  
9550                  0            2               4.0    591  

[9551 rows x 7 columns]

### Train test split

In [12]:
from sklearn.model_selection import train_test_split
df.columns

Index(['Average Cost for two', 'Has Table booking', 'Has Online delivery',
       'Is delivering now', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [13]:
input_columns = ['Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Is delivering now',
       'Price range', 'Votes']
output_columns = ['Aggregate rating']

x = df[input_columns]
y = df[output_columns]
split_test_size = 0.2


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = split_test_size,random_state=42)

In [14]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7640, 6)
(1911, 6)
(7640, 1)
(1911, 1)


In [15]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

x_train = imputer.fit_transform(x_train)
x_test = imputer.fit_transform(x_test)



In [16]:
x_train[0:3]

array([[1.9e+03, 1.0e+00, 0.0e+00, 0.0e+00, 3.0e+00, 5.6e+01],
       [1.0e+02, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 4.0e+00],
       [1.0e+02, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00]])

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test =scaler.transform(x_test)

### check the proportion

In [18]:
print('{0:0.2f}% in training set'.format((len(x_train)/len(df.index))*100))


print('{0:0.2f}% in testing set'.format((len(x_test)/len(df.index))*100))

79.99% in training set
20.01% in testing set


In [19]:
df['Aggregate rating'].describe()

count    9551.000000
mean        2.666370
std         1.516378
min         0.000000
25%         2.500000
50%         3.200000
75%         3.700000
max         4.900000
Name: Aggregate rating, dtype: float64

In [20]:
print("Train mean:", y_train.mean())
print("Test mean :", y_test.mean())

print("Train min/max:", y_train.min(), y_train.max())
print("Test min/max :", y_test.min(), y_test.max())


Train mean: Aggregate rating    2.659987
dtype: float64
Test mean : Aggregate rating    2.691889
dtype: float64
Train min/max: Aggregate rating    0.0
dtype: float64 Aggregate rating    4.9
dtype: float64
Test min/max : Aggregate rating    0.0
dtype: float64 Aggregate rating    4.9
dtype: float64


## Train  the model using linear Regression

In [21]:
lr_model= LinearRegression()
lr_model

LinearRegression()

In [22]:
# training the model
lr_model.fit(x_train,y_train)

LinearRegression()

In [23]:
y_pred = lr_model.predict(x_test)
y_pred = y_pred.ravel()
y_pred

array([1.92426042, 3.25299611, 2.56702034, ..., 2.54946316, 3.4229489 ,
       3.48456572], shape=(1911,))

In [24]:
# R squared error
error_score = metrics.r2_score(y_test, y_pred)
print("R - squared error : ",error_score)

R - squared error :  0.2634972122459106


In [25]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 1.6763606165950804


## decision tree regression

In [26]:
dtr_model = DecisionTreeRegressor()
dtr_model

DecisionTreeRegressor()

In [27]:
# training the model
dtr_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [28]:
y_train_pred = dtr_model.predict(x_train)
y_test_pred = dtr_model.predict(x_test)
y_test_pred = y_test_pred.ravel()
y_test_pred

array([2.4       , 3.66666667, 3.6       , ..., 3.14      , 3.7       ,
       4.1       ], shape=(1911,))

In [29]:
# R squared error
error_score = metrics.r2_score(y_test, y_test_pred)
print("R - squared error : ",error_score)

R - squared error :  0.9109009148870781


In [30]:
mse = mean_squared_error(y_test, y_test_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.20279922865387126


In [31]:
input_data = [4000, 1, 0, 0, 4, 270]

input_array = pd.DataFrame([input_data])

# Apply the same imputer and scaler to new data
input_array = imputer.fit_transform(input_array)
input_array = scaler.transform(input_array)


prediction = dtr_model.predict(input_array)
prediction

array([4.4])

## Conclusion

The Decision Tree Regression model performed better than Linear Regression.
Food quality and service ratings were the most influential factors affecting
restaurant aggregate ratings.


In [33]:
import pickle 
# save model
with open('dtr_model.pkl','wb') as f:
    pickle.dump(dtr_model, f)
# save scaler
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
# save imputer
with open('imputer.pkl', 'wb') as f:
    pickle.dump(imputer, f)